on:
  schedule:
  - cron: 15 7 * * *
name: Update
jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: set remote url
      run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: package-update
      uses: taichi/actions-package-update@master
      env:
        AUTHOR_EMAIL: roni.c.castro@gmail.com
        AUTHOR_NAME: Roni
        EXECUTE: "true"
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        UPDATE_COMMAND: yarn
        LOG_LEVEL: debug
      with:
        args: upgrade --latest
